### ISSUE TITLE
Image Re-link not working

### ISSUE THREAD

**Issue by MilkClouds** [connertennery/Notion-to-Obsidian-Converter#27]
I used this to exported notion files, with image styled with(I've not edit anything after exporting from notion)

```
![Untitled](Perceiver%20IO%20A%20General%20Architecture%20for%20Structured%206d4d05e8eeef470f9a3148f92e0250b2/Untitled.png)
```

but these are converted to `![[Untitled]]` and this seems not working well.
I'm using Windows 11.
Is there anybody treating this issue?

**Comment by A1ic3-g** [comment]
I'm also having this issue

**Comment by connertennery** [comment]
Hi @MilkClouds and @A1ic3-g! Thanks for submitting the issue and providing a good example. I can't guess at the problem right away, but I think it might be an issue with the script not selecting the right path due to the subdirectory that contains the `Untitled.png` image. I'll try to patch this soon.

**Comment by connertennery** [comment]
Hey @MilkClouds and @A1ic3-g, I just got a chance to look at this tonight and I believe I can see what the problem is, but to make sure I'm understanding the right scenario so I can fix it, would either of you be willing to submit an example export with this issue? I'm unable to create any exports from Notion that create the same link structure.

**Comment by connertennery** [comment]
@MilkClouds Thank you for the example export and for the pull request. :) I think I have a fix that should work well without disabling regex. I tested it a few times and tried to tweak the links in your export but it all seems to work well.

**Comment by A1ic3-g** [comment]
@connertennery I can confirm the fix works for my notion export :)

**Comment by UtilityWorlds** [comment]
Hi, I've had another problem about this:

Link Before Convert: 
![Draw call batching.png]
(Optimize%20Draw%20Calls%20385de85d71e1473db332c309eb5ed696/Draw_call_batching.png)

Link After Convert: 
![[/Draw call batching.png]]

But the name of the image is "Draw_call_batching.png", so it doesn't work as expected.

**Comment by janghwan** [comment]
I'm having the same issue as @carlos-truong  mentioned. please re-open this issue. I actually made a fix.
